### ISSUE TITLE
Use git filter-branch to rebuild this repo and retain all old commit history

### ISSUE THREAD

**Issue by brendanheywood** [jmcgettrick/moodle-block_turnitin#2]
So instead of 1 commit we get full history:

https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

Because this repo is brand new and hasn't yet been forked much or whatever I'd force push to fix it up. Ditto for the other sister repos for the mod and plagiarism plugins

**Comment by jmcgettrick** [comment]
Hi Brendan, thanks for this.
I'll do this when the mod & plagiarism folders are split out. I'm happy enough for the block to stay as is, as we don't expect anything to change with it short term but it might be useful to re-do this repository as a trial run.

**Comment by brendanheywood** [comment]
cool. I think it's good to redo it for a bunch of meta reasons as well like better git blame / bisecting and also for stuff like getting better stats out of github:

https://github.com/jmcgettrick/MoodleDirectV2/graphs/contributors
vs
https://github.com/jmcgettrick/moodle-block_turnitin/graphs/contributors

If you do plan on doing it at all it's probably best to do it asap so there is less window for people to get the borked history in the meantime, and less people to tell about the forced push. I've found it can also be a little tedious getting this right the first time, so here's a complete trial run:

```
git clone git@github.com:jmcgettrick/MoodleDirectV2.git
cd MoodleDirectV2/
git reset --hard 1980aefd8f9d6d
git filter-branch --prune-empty --subdirectory-filter blocks/turnitin/ master
git remote add github git@github.com:brendanheywood/moodle-block_turnitin.git
git push github
```

https://github.com/brendanheywood/moodle-block_turnitin

**Comment by jmcgettrick** [comment]
Thanks Brendan.
We'll get this done.

**Comment by jmcgettrick** [comment]
All repos are now split out.

Cheers
