### ISSUE TITLE
block-turnitin install requirements

### ISSUE THREAD

**Issue by hitteshahuja** [jmcgettrick/moodle-block_turnitin#5]
Hi john,
After you split the 3 plugin repositories , you renamed the module to mod_turnitintool but under blocks/turnitin/version.php it still lists mod_turnitintool**two** as a requirement. This should be changed to mod_turnitintool . 

Thanks,
Hittesh

**Comment by hitteshahuja** [comment]
Actually this is an error on my side. I didnt see there was also a turnitintooltwo repo too !!

**Comment by jmcgettrick** [comment]
No problem Hittesh! The turnitintool one is my fork of our v1 code.
